#!/bin/sh

root=../../../../out
export LD_LIBRARY_PATH=$root/lib:$HOME/local/lib
soar=$root/bin/s

while test -n "$1"
do
	case "$1" in
	-g)
		debug=1
		;;
	-s)
		sim=1
		;;
	esac
	shift
done

if test "$sim" == "1"
then
	python splintersim.py &
	envid=$!
	#socat system:./splintersim unix-connect:env,retry=100 &
else
	socat system:"java RobotClient" unix-connect:env,retry=100 &
fi

if test "$debug" == "1"
then
	gdb --args $soar robot.soar
else
	$soar robot.soar
fi

if test "$sim" != "1"
then
	pids=`ps x | awk '/RobotClient/ { print $1 }'`
	if test -n "$pids"
	then
		kill $pids
	fi
else
	kill $envid
fi
