#!/usr/bin/python
import glob

Import('env')
env = env.Copy()

# $JAVAC $JAVACFLAGS -d ${TARGET.attributes.java_classdir} -sourcepath ${SOURCE.dir.rdir()} $SOURCES
env.Replace(JAVACCOM = '$JAVAC $JAVACFLAGS -d ${TARGET.attributes.java_classdir} -classpath Core/ClientSMLSWIG/Java/sml.jar:SoarLibrary/bin/swt.jar -sourcepath ${SOURCE.dir.rdir()} $SOURCES')

env.Java(target = 'classes', source = '.')

# The usual jar command does not work. It only finds and jars class files and we need a bunch of other junk.
# If you list files specifically, it includes a full path with them.
#env.Append(JARCHDIR = 'Tools/SoarJavaDebugger/classes')
#SoarJavaDebugger = env.Jar(target = 'SoarJavaDebugger.jar', source = ['classes', 'JarManifest', ])

env.Command('#Tools/SoarJavaDebugger/SoarJavaDebugger.jar', 'classes', '#Tools/SoarJavaDebugger/copyFiles.sh')
env.Command('#Tools/SoarJavaDebugger/SoarJavaDebugger.jar', 'classes', 'jar cvfm Tools/SoarJavaDebugger/SoarJavaDebugger.jar Tools/SoarJavaDebugger/JarManifest -C Tools/SoarJavaDebugger/classes .')
env.Install('#SoarLibrary/bin', '#Tools/SoarJavaDebugger/SoarJavaDebugger.jar')
