#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Append(CPPFLAGS = ' -fno-strict-aliasing')
env.Prepend(CPPPATH = ['src', 'include', '../gSKI/include', '../CLI/include'])

env.Library('SoarKernel', glob.glob('src/*.cpp'))
