#ifndef AUTOCONF_COMPATIBILITY_H
#define AUTOCONF_COMPATIBILITY_H

/* autoconf_compatibility.h
 *
 * Processes macros and symbols generated by autoconf to set up
 * various includes, macros, functions, and structures.
 */
 
#ifdef HAVE_CONFIG_H

/* AC_HEADER_STDC */
# if STDC_HEADERS
#  include <string.h>
# else // STDC_HEADERS
#  if !HAVE_STRCHR
#   define strchr index
#   define strrchr rindex
#  endif // HAVE_STRCHR
char *strchr (), *strrchr ();
#  if !HAVE_MEMCPY
#   define memcpy(d, s, n) bcopy ((s), (d), (n))
#   define memmove(d, s, n) bcopy ((s), (d), (n))
#  endif // HAVE_MEMCPY
# endif // STDC_HEADERS

/* AC_HEADER_STDBOOL */
# if HAVE_STDBOOL_H 
#  include <stdbool.h> 
# else // HAVE_STDBOOL_H
#  if ! HAVE__BOOL 
#   ifdef __cplusplus 
typedef bool _Bool; 
#   else // __cplusplus
typedef unsigned char _Bool; 
#   endif // __cplusplus
#  endif // HAVE__BOOL
# define bool _Bool 
# define false 0 
# define true 1 
# define __bool_true_false_are_defined 1 
# endif // HAVE_STDBOOL_H

/* AC_HEADER_TIME */
#if TIME_WITH_SYS_TIME
# include <sys/time.h>
# include <time.h>
#else
# if HAVE_SYS_TIME_H
#  include <sys/time.h>
# else
#  include <time.h>
# endif
#endif

#else // HAVE_CONFIG_H

# ifdef _MSC_VER
/* Compiling on the MSVC platform */
# endif // MSC_VER

#endif // HAVE_CONFIG_H

#endif // AUTOCONF_COMPATIBILITY_H
