#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '../SoarKernel/include', 
		       '../gSKI/src', 
		       '../gSKI/include', 
		       '../ElementXML/include', 
		       '../ConnectionSML/include', 
		       '../KernelSML/include', ])

env.Library('CommandLineInterface', glob.glob('src/*.cpp'))
