	//"add-wme aw",
	//"alias a",
	//"cd chdir", 
	//"command-to-file ctf",
	//"default-wme-depth set-default-depth",
	//"excise ex",
	//"explain-backtraces eb",
	//"firing-counts fc",
	//"gds-print gds_print",
	//"help h",
	//"help man",
	//"help ?",
	//"indifferent-selection inds",
	//"init-soar init",
	//"init-soar is",
	//"learn l",
	//"ls dir",
	//"print p",
	//"print --chunks pc",
	//"preferences pr",
	//"preferences --object support",
	//"pwd topd",
	//"pwatch pw",
	//"quit exit",
	//"run -d step",
	//"run -d d", 
	//"run -e e",
	//"remove-wme rw",
	//"rete-net rn",
	//"soarnews sn",
	//"stats st", 
	//"start-system start",
	//"stop-soar stop", 
	//"stop-soar ss", 
	//"stop-soar interrupt",
	//"unalias un",
	//"watch w",
	//"print -i wmes",
	//"print -v -d 100 varprint",
