#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 'include', '../ElementXML/include', '../ConnectionSML/include', ])

env.Library('ClientSML', glob.glob('src/*.cpp'))
