#!/usr/bin/python
import glob
import distutils.sysconfig

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = [
			'#Core/ClientSML/include',
			'#Core/ElementXML/include',
			'#Core/ConnectionSML/include',
			distutils.sysconfig.get_python_inc()
			])
env.Append(CXXFLAGS = ' -Wno-unused -fno-strict-aliasing')

libadd = [
	   'ClientSML',
	   'ConnectionSML',
	   'ElementXML',
	   ]

libpath = [ 
	    '#Core/ClientSML',
	    '#Core/ConnectionSML',
	    '#Core/ElementXML', 
	    ]

swigflags = '-c++ -python -Wall -ICore/ClientSML/include -ICore/ElementXML/include -ICore/ConnectionSML/include '

Python_sml_ClientInterface = env.SharedLibrary('Python_sml_ClientInterface', 
					       glob.glob('*.i'), 
					       LIBS = libadd, 
					       LIBPATH = libpath, 
					       SWIGFLAGS = swigflags, 
					       SWIGCXXFILESUFFIX = "_wrap.cpp")
env.Install('#SoarLibrary/lib', Python_sml_ClientInterface)
env.Install('#SoarLibrary/bin', 'Python_sml_ClientInterface.py')

