#!/usr/bin/python
import glob
import SoarSCons

Import('env')
env = env.Clone()

theJar = '#Tools/TestJavaSML/TestJavaSML.jar';
sources = SoarSCons.JavaSources('src')

env.Command(theJar, sources, 'ant', chdir=1)
env.Clean(theJar, '#Tools/TestJavaSML/build')

