#!/usr/bin/python
import glob
import shutil
import SoarSCons
import sys

Import('env')
env = env.Clone()

theJar = '#Environments/JavaMissionaries/JavaMissionaries.jar';
sources = glob.glob('src/mac/*')

env.Command(theJar, sources, 'ant', chdir=1)
env.Clean(theJar, '#Environments/JavaMissionaries/build')
env.Install('#SoarLibrary/bin', theJar)

