#!/usr/bin/python
# Project: Soar <http://soar.googlecode.com>
# Author: Jonathan Voigt <voigtjr@gmail.com>
#
Import('compEnv')
s = compEnv.Program('s', Glob('*.cpp'))
compEnv.Install('$PREFIX/bin', s)

