#!/usr/bin/python
import glob

Import('env')
env = env.Copy()
env.Prepend(CPPPATH = ['src', 
		       'include', 
		       '../SoarKernel/include',
		       '../gSKI/src',
		       '../gSKI/include',
		       '../CLI/include',
		       '../ElementXML/include',
		       '../ConnectionSML/include'])

libadd1 = [ 'SoarKernel',
	   'gSKI',
	   'CommandLineInterface',
	   'ConnectionSML',
	   'ElementXML', ]

libadd2 = [
	   'ElementXML',
	   'ConnectionSML',
	   'CommandLineInterface',
	   'gSKI',
	   'SoarKernel', 
	   ]

libpath = [ '../SoarKernel',
	    '../gSKI',
	    '../CLI',
	    '../ConnectionSML',
	    '../ElementXML', ]

env.SharedLibrary('SoarKernelSML', glob.glob('src/*.cpp'), LIBS = libadd2, LIBPATH = libpath)
